#!/usr/bin/env python3

# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.


TEST_CASES = [("abcd", "abcde", "e")]


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_sum = 0
        t_sum = 0
        for idx, val in enumerate(s):
            s_sum += ord(val)
            t_sum += ord(t[idx])
        t_sum += ord(t[-1])

        return chr(t_sum - s_sum)


for test_case in TEST_CASES:
    assert Solution().findTheDifference(test_case[0], test_case[1]) == test_case[2]
